name: 'setup-solbuild'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v2
    - run: chmod +x ${{ github.action_path }}/setup.sh
      shell: bash
    - run: ${{ github.action_path }}/setup.sh
      shell: bash
