name: 'setup-solbuild'
description: 'Setup solbuild, the Solus package build system.'
branding:
  icon: 'package'  
  color: 'blue'
inputs:
  packager:
    description: 'Name of the packager.'
    required: false
    default: 'user'
  email:
    description: 'Email of the packager.'
    required: false
    default: 'user@example.com'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v2
    - run: ${{ github.action_path }}/setup.sh "${{ inputs.packager }}" "${{ inputs.email }}"
      shell: bash
